export const ADD_CART = "ADD_CART";
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS";
export const ADD_CART_FAILED = "ADD_CART_FAILED";

export const UPDATE_CART = "UPDATE_CART";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const UPDATE_CART_FAILED = "UPDATE_CART_FAILED";

export const GET_CARTS = "GET_CARTS";
export const GET_CARTS_SUCCESS = "GET_CARTS_SUCCESS";
export const GET_CARTS_FAILED = "GET_CARTS_FAILED";

export const DELETE_CART = "DELETE_CART";
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";
export const DELETE_CART_FAILED = "DELETE_CART_FAILED";

export const EMPTY_CART = "EMPTY_CART";
